#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Daiki Tajima t.dai.1215@gmail.com
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for n in sys.stdin:
  try:
    ans += int(n)**2
  except:
    ans += float(n)**2
print(ans)
